---

esphome:
  name: sound_machine

esp8266:
  board: nodemcuv2

uart:
  tx_pin: D2
  rx_pin: D5
  baud_rate: 9600

dfplayer:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  platform: esphome

web_server:
  port: 80

# Switches for tracks to play
switch:
  - platform: template
    name: "Lullaby"
    id: lullaby
    optimistic: true
    turn_on_action:
      then:
        - switch.turn_off: womb_sounds
        - delay: 1s
        - dfplayer.play_folder:
            folder: 1
            loop: true
    turn_off_action:
      then:
        - dfplayer.stop
  - platform: template
    name: "Womb Sounds"
    id: womb_sounds
    optimistic: true
    turn_on_action:
      then:
        - switch.turn_off: lullaby
        - delay: 1s
        - dfplayer.play_folder:
            folder: 2
            loop: true
    turn_off_action:
      then:
        - dfplayer.stop

# Physical buttons for local override
binary_sensor:
  - platform: gpio
    name: Button
    internal: true
    pin:
      number: 5
      mode: INPUT_PULLUP
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_release:
      then:
        - switch.toggle: lullaby
  - platform: gpio
    name: Button
    internal: true
    pin:
      number: 12
      mode: INPUT_PULLUP
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_release:
      then:
        - switch.toggle: womb_sounds

sensor:
  # Reports the WiFi signal strength
  - platform: wifi_signal
    name: Sound Machine Signal
    update_interval: 60s
  # Reports how long the device has been powered (in minutes)
  - platform: uptime
    name: Sound Machine Uptime
    filters:
      - lambda: return x / 60.0;
    unit_of_measurement: minutes

text_sensor:
  - platform: version
    name: Sound Machine ESPHome Version